repos:
- repo: https://github.com/antonbabenko/pre-commit-terraform
  rev: v1.83.5
  hooks:
    #- id: tfupdate
    - id: terraform_fmt
    - id: terraform_validate
      args:
        - --hook-config=--retry-once-with-cleanup=true
    - id: terrascan
    - id: terraform_tfsec
    # - id: terraform_tflint
    #   args:
    #     - --args=--module
    #     - --args=--enable-rule=terraform_documented_variables
    - id: terraform_docs
      args:
        - --hook-config=--path-to-file=README.md
        - --hook-config=--add-to-existing-file=true
        - --hook-config=--create-file-if-not-exist=true
    