name: Changelog CI

on:
  push:
    branches:
      - "release/**"
    paths-ignore:
      - "*.md"

  workflow_call:
  workflow_dispatch:

jobs:
  generate_changelog:
    runs-on: large-ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0.10.2
        with:
          versionSpec: "5.12.0"

      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0.10.2

      - name: Run Changelog CI
        uses: saadmk11/changelog-ci@v1.1.2
        with:
          config_file: .github/config/changelog-config.yaml
          release_version: ${{ steps.gitversion.outputs.majorMinorPatch }}
          github_token: ${{ secrets.GITHUB_TOKEN  }}

  notify:
    runs-on: ubuntu-latest
    needs: [generate_changelog]
    if: always()

    steps:
      - name: Notify Slack
        uses: act10ns/slack@v2
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        with:
          status: ${{ job.status }}
          channel: "#phoenix-builds"
        if: always()
